export default function () {
  return {
    order: {
      // name: null,
      // phone: null,
      // address: null,
      // apartment: null,
      // time: null,
      // early: true,
      // payment: '1',
      // comment: null,
      isCostume: false,
      // forks: 1,
      promocode: '',
    },
    orderProducts: [],
    orderMenu: [],
    categoriesMenu: [],
    promoCodes: [],
    promoCode: {
      value: null,
      product: null,
      hasUsed: false,
    },
    currentOrder: {
      id: null,
      // sourceId: JSON.parse(process.env.sourceList).SITE,
      comment: null,
      isDelete: false,
      isApprove: false,
      needConfirm: false,
      fullForm: true,
      clientInfo: {
        client: {
          id: null,
          name: null,
          // hash: sha256(new Date().toString()).toString(),
          token: null,
        },
        phone: '+7 (',
        phoneString: null,
        addressString: null,
        address: {
          id: null,
          apartment: null,
          dadata: null,
        },
      },
      deliveryInfo: {
        date: null,
        time: null,
        isCheck: false,
        dateCheck: null,
        // type: JSON.parse(process.env.DELIVERY_TYPE_LIST).DELIVERY,
        department: null,
      },
      payments: [
        {
          // type: { id: JSON.parse(process.env.PAIMENT_TYPES).CASH },
          sum: null,
          paymentLink: null,
        },
      ],
      discount: null,
      orderStatuses: [],
      products: [],
      forks: '',
      early: true,
      useBonus: 0,
    },
  };
}
